version: '3.8'

services:
  auth_app:
    build: 
      dockerfile: Dockerfile
    image: auth_app:0.0.0
    container_name: ${ENV_PROJ_NAME}_${ENV_APP_CONT_NAME_AUTH}
    ports:
      - ${ENV_APP_PORT_AUTH}:${APP_PORT}
    volumes:
      - .:/app
    command: gunicorn backend.services.auth.main:web_app -c backend/services/auth/config/gunicorn.conf.py
    restart: unless-stopped
  
  fine_app:
    build: 
      dockerfile: Dockerfile
    image: fine_app:0.0.0
    container_name: ${ENV_PROJ_NAME}_${ENV_APP_CONT_NAME_FINE}
    ports:
      - ${ENV_APP_PORT_FINE}:${APP_PORT}
    volumes:
      - .:/app
    command: gunicorn backend.services.fine.main:web_app -c backend/services/fine/config/gunicorn.conf.py
    restart: unless-stopped

  auth_mongo:
    image: mongo:6.0
    container_name: ${ENV_PROJ_NAME}_${ENV_MONGO_CONT_NAME_AUTH}
    ports:
      - ${ENV_MONGO_PORT_AUTH}:27017
    volumes:
      - ./data/auth/mongo:/data/db
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  fine_mongo:
    image: mongo:6.0
    container_name: ${ENV_PROJ_NAME}_${ENV_MONGO_CONT_NAME_FINE}
    ports:
      - ${ENV_MONGO_PORT_FINE}:27017
    volumes:
      - ./data/fine/mongo:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always

  # traefik_proxy:
  #   image: traefik:2.9
  #   ports:
  #     - 3003:80
  #   labels:
  #     - "traefik.http.routers.traefik.rule=Host(`localhost.com`)"
  #   container_name: traefik_proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./traefik/traefik.toml:/etc/traefik/traefik.toml
  #     - ./traefik/log:/var/log
  
  # ambassador_gateway:
  #   image: datawire/ambassador:1.14
  #   command: --port 8080
  #   volumes:
  #     - ./gateway-config:/ambassador/ambassador-config
  #   environment:
  #     - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
  #   labels:
  #     - "traefik.http.routers.gateway.rule=Host(`localhost.com`) && PathPrefix(`/api`)"
  #     - "traefik.http.middlewares.gateway-stripprefix.stripprefix.prefixes=/api"
  #     - "traefik.http.routers.gateway.middlewares=gateway-stripprefix@docker"
  #     - "traefik.http.routers.gateway.service=gateway"
  #     - "traefik.http.services.gateway.loadbalancer.server.port=8080"
  #     - "traefik.docker.network=external-proxy"
  #   container_name: ambassador_gateway